
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  #host: localhost
  #username: Ballad


#
development:
  <<: *default
  database: The-Ballad-Trail_development

#
test:
  <<: *default
  database: The-Ballad-Trail_test


#
production:
  <<: *default
  database: The-Ballad-Trail_production
  #username: The-Ballad-Trail
  #password: <%= ENV['THE-BALLAD-TRAIL_DATABASE_PASSWORD'] %>
